version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.1-fpm
    container_name: php_container
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer_container
    volumes:
      - ./app:/app
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_container
    ports:
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
